// Code generated by CraneSched/scripts/generate_execution_flow_schema.py. DO NOT EDIT.
// Source: CraneSched/schemas/execution-flow/v1.yaml
// SHA256: 483eab1c63b4ca98c77238f960828a1efbaaff8e2a826da397afd2f3ff4131b7

package main

const (
	executionFlowSchemaSHA256       = "483eab1c63b4ca98c77238f960828a1efbaaff8e2a826da397afd2f3ff4131b7"
	executionFlowSchemaName         = "flow/v1"
	executionFlowSchemaVersion      = "v1"
	executionFlowWirePrefix         = "flow/v1/"
	executionFlowHeartbeatPoint     = "flow/v1/pipeline/heartbeat"
	executionFlowPipelineFaultPoint = "flow/v1/pipeline/fault"
)

type executionFlowReasonCode string

const (
	executionFlowReasonArrayJob                      executionFlowReasonCode = "array-job"
	executionFlowReasonCancelledBeforeAllocation     executionFlowReasonCode = "cancelled-before-allocation"
	executionFlowReasonContainerJob                  executionFlowReasonCode = "container-job"
	executionFlowReasonExtraCommonStep               executionFlowReasonCode = "extra-common-step"
	executionFlowReasonFlowEnvironmentIdMismatch     executionFlowReasonCode = "flow_environment_id_mismatch"
	executionFlowReasonInvalidAttributeType          executionFlowReasonCode = "invalid_attribute_type"
	executionFlowReasonInvalidEnumValue              executionFlowReasonCode = "invalid_enum_value"
	executionFlowReasonInvalidEventSequence          executionFlowReasonCode = "invalid_event_sequence"
	executionFlowReasonInvalidEventTime              executionFlowReasonCode = "invalid_event_time"
	executionFlowReasonInvalidFlowId                 executionFlowReasonCode = "invalid_flow_id"
	executionFlowReasonInvalidFlowSchema             executionFlowReasonCode = "invalid_flow_schema"
	executionFlowReasonInvalidIntegerAttribute       executionFlowReasonCode = "invalid_integer_attribute"
	executionFlowReasonInvalidSpanId                 executionFlowReasonCode = "invalid_span_id"
	executionFlowReasonMissingFlowEnvironmentId      executionFlowReasonCode = "missing_flow_environment_id"
	executionFlowReasonMissingProducer               executionFlowReasonCode = "missing_producer"
	executionFlowReasonMissingRequiredAttribute      executionFlowReasonCode = "missing_required_attribute"
	executionFlowReasonMissingServiceInstance        executionFlowReasonCode = "missing_service_instance"
	executionFlowReasonMissingServiceLogicalInstance executionFlowReasonCode = "missing_service_logical_instance"
	executionFlowReasonNonBatchJob                   executionFlowReasonCode = "non-batch-job"
	executionFlowReasonPointNameMismatch             executionFlowReasonCode = "point_name_mismatch"
	executionFlowReasonProducerMismatch              executionFlowReasonCode = "producer_mismatch"
	executionFlowReasonRequeueAttempt                executionFlowReasonCode = "requeue-attempt"
	executionFlowReasonRequeueEnabled                executionFlowReasonCode = "requeue-enabled"
	executionFlowReasonUnexpectedAttribute           executionFlowReasonCode = "unexpected_attribute"
	executionFlowReasonUnknownPoint                  executionFlowReasonCode = "unknown_point"
)

var generatedExecutionFlowAttributeTypes = map[string]string{
	"attempt":     "int64",
	"job_id":      "int64",
	"node_id":     "string",
	"operation":   "enum",
	"outcome":     "enum",
	"reason_code": "enum",
	"status":      "int64",
	"step_id":     "int64",
	"task_id":     "int64",
}

var generatedExecutionFlowEnumValues = map[string]map[string]struct{}{
	"operation": {
		"alloc-jobs":              {},
		"alloc-steps":             {},
		"allocate":                {},
		"cancel-pending-job":      {},
		"daemon-cleanup":          {},
		"daemon-configure":        {},
		"daemon-terminal":         {},
		"embedded-db-commit":      {},
		"embedded-db-finalize":    {},
		"enqueue-status":          {},
		"execute-step":            {},
		"execute-steps":           {},
		"exit-supervisor":         {},
		"finalize-step":           {},
		"finalize-task":           {},
		"fork-supervisor":         {},
		"free-jobs":               {},
		"free-step":               {},
		"free-steps":              {},
		"initialize":              {},
		"initialize-supervisor":   {},
		"install-job":             {},
		"install-step":            {},
		"job-cleanup":             {},
		"job-terminal":            {},
		"mongodb-finalize":        {},
		"observe-supervisor-exit": {},
		"observe-task-exit":       {},
		"prepare-task":            {},
		"release-resources":       {},
		"remove-job":              {},
		"requeue":                 {},
		"send-status-change":      {},
		"shutdown-supervisor":     {},
		"spawn-task":              {},
		"state-machine":           {},
		"status-change":           {},
		"step-cleanup":            {},
		"step-configure":          {},
		"step-terminal":           {},
		"submit":                  {},
		"submit-common-step":      {},
		"supervisor-epilog":       {},
	},
	"outcome": {
		"accepted":          {},
		"applied":           {},
		"cleanup-failure":   {},
		"completed":         {},
		"craned-down":       {},
		"early-cancel":      {},
		"exit":              {},
		"exited":            {},
		"failure":           {},
		"persisted":         {},
		"pre-start-failure": {},
		"queued":            {},
		"rejected":          {},
		"requested":         {},
		"rpc-failure":       {},
		"signal":            {},
		"skipped":           {},
		"started":           {},
		"success":           {},
		"unsupported":       {},
	},
	"reason_code": {
		"array-job":                        {},
		"cancelled-before-allocation":      {},
		"container-job":                    {},
		"extra-common-step":                {},
		"flow_environment_id_mismatch":     {},
		"invalid_attribute_type":           {},
		"invalid_enum_value":               {},
		"invalid_event_sequence":           {},
		"invalid_event_time":               {},
		"invalid_flow_id":                  {},
		"invalid_flow_schema":              {},
		"invalid_integer_attribute":        {},
		"invalid_span_id":                  {},
		"missing_flow_environment_id":      {},
		"missing_producer":                 {},
		"missing_required_attribute":       {},
		"missing_service_instance":         {},
		"missing_service_logical_instance": {},
		"non-batch-job":                    {},
		"point_name_mismatch":              {},
		"producer_mismatch":                {},
		"requeue-attempt":                  {},
		"requeue-enabled":                  {},
		"unexpected_attribute":             {},
		"unknown_point":                    {},
	},
}

var generatedExecutionFlowPoints = map[string]executionFlowPointSpec{
	"craned/job/installed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"craned/job/removed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"craned/status/send_result": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"craned/step/cleanup_finished": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/cleanup_started": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation"},
	},
	"craned/step/execute_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/free_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/install_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/installed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/exit_observed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/forked": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/ready": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/accepted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/alloc_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/allocated": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/allocation_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/embedded_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/free_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/mongo_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/resources_released": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/terminal": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "status", "operation", "outcome"},
	},
	"ctld/job/unsupported": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome", "reason_code"},
	},
	"ctld/status/applied": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"ctld/status/received": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"ctld/step/all_completing": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "operation", "outcome"},
	},
	"ctld/step/all_configured": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "operation", "outcome"},
	},
	"ctld/step/all_terminal": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "status", "operation"},
	},
	"ctld/step/alloc_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/execute_requested": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/execute_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/free_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"pipeline/fault": {
		Producer:           "frontend",
		RequiredAttributes: []string{"reason_code"},
	},
	"supervisor/step/all_tasks_finalized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/step/completing_enqueued": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/step/epilog_finished": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"supervisor/step/execute_started": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"supervisor/step/exiting": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/step/initialized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/step/shutdown_received": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/task/exit_observed": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
	"supervisor/task/finalized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/task/prepared": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
	"supervisor/task/spawned": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
}

type generatedExecutionFlowCatalogData struct{}

var generatedExecutionFlowCatalog executionFlowSchemaCatalog = generatedExecutionFlowCatalogData{}

func (generatedExecutionFlowCatalogData) SchemaSHA256() string {
	return executionFlowSchemaSHA256
}

func (generatedExecutionFlowCatalogData) SchemaName() string {
	return executionFlowSchemaName
}

func (generatedExecutionFlowCatalogData) SchemaVersion() string {
	return executionFlowSchemaVersion
}

func (generatedExecutionFlowCatalogData) WirePrefix() string {
	return executionFlowWirePrefix
}

func (generatedExecutionFlowCatalogData) HeartbeatPoint() string {
	return executionFlowHeartbeatPoint
}

func (generatedExecutionFlowCatalogData) PipelineFaultPoint() string {
	return executionFlowPipelineFaultPoint
}

func (generatedExecutionFlowCatalogData) Point(name string) (executionFlowPointSpec, bool) {
	point, ok := generatedExecutionFlowPoints[name]
	if !ok {
		return executionFlowPointSpec{}, false
	}
	point.RequiredAttributes = append([]string(nil), point.RequiredAttributes...)
	return point, ok
}

func (generatedExecutionFlowCatalogData) AttributeType(name string) (string, bool) {
	attributeType, ok := generatedExecutionFlowAttributeTypes[name]
	return attributeType, ok
}

func (generatedExecutionFlowCatalogData) AllowsAttribute(name string) bool {
	_, ok := generatedExecutionFlowAttributeTypes[name]
	return ok
}

func (generatedExecutionFlowCatalogData) AllowsEnumValue(attribute string, value string) bool {
	values, ok := generatedExecutionFlowEnumValues[attribute]
	if !ok {
		return false
	}
	_, ok = values[value]
	return ok
}
