// Code generated by CraneSched/scripts/generate_execution_flow_schema.py. DO NOT EDIT.
// Source: CraneSched/schemas/execution-flow/v1.yaml
// SHA256: 850ffaaf06e57ab7eabc34a2fb17cde92c172d45de7ef886fa05333f929f71c9

package main

const (
	executionFlowSchemaSHA256                   = "850ffaaf06e57ab7eabc34a2fb17cde92c172d45de7ef886fa05333f929f71c9"
	executionFlowSchemaName                     = "flow/v1"
	executionFlowSchemaVersion                  = "v1"
	executionFlowWirePrefix                     = "flow/v1/"
	executionFlowHeartbeatPoint                 = "flow/v1/pipeline/heartbeat"
	executionFlowPipelineFaultPoint             = "flow/v1/pipeline/fault"
	executionFlowEnvelopeEventSequence          = "event_sequence"
	executionFlowEnvelopeFlowID                 = "flow_id"
	executionFlowEnvelopeFlowSchema             = "flow_schema"
	executionFlowEnvelopePoint                  = "point"
	executionFlowEnvelopeProducer               = "producer"
	executionFlowEnvelopeServiceInstance        = "service_instance"
	executionFlowEnvelopeServiceLogicalInstance = "service_logical_instance"
	executionFlowStorageEventTimeUnixNano       = "event_time_unix_nano"
	executionFlowStorageFlowEnvironmentID       = "flow_environment_id"
	executionFlowStorageFlowInstanceSlot        = "flow_instance_slot"
	executionFlowStorageFlowSlot                = "flow_slot"
)

type executionFlowReasonCode string

const (
	executionFlowReasonArrayJob                      executionFlowReasonCode = "array-job"
	executionFlowReasonCancelledBeforeAllocation     executionFlowReasonCode = "cancelled-before-allocation"
	executionFlowReasonContainerJob                  executionFlowReasonCode = "container-job"
	executionFlowReasonExtraCommonStep               executionFlowReasonCode = "extra-common-step"
	executionFlowReasonFlowEnvironmentIdMismatch     executionFlowReasonCode = "flow_environment_id_mismatch"
	executionFlowReasonInvalidAttributeType          executionFlowReasonCode = "invalid_attribute_type"
	executionFlowReasonInvalidEnumValue              executionFlowReasonCode = "invalid_enum_value"
	executionFlowReasonInvalidEventSequence          executionFlowReasonCode = "invalid_event_sequence"
	executionFlowReasonInvalidEventTime              executionFlowReasonCode = "invalid_event_time"
	executionFlowReasonInvalidFlowId                 executionFlowReasonCode = "invalid_flow_id"
	executionFlowReasonInvalidFlowSchema             executionFlowReasonCode = "invalid_flow_schema"
	executionFlowReasonInvalidIntegerAttribute       executionFlowReasonCode = "invalid_integer_attribute"
	executionFlowReasonInvalidSpanId                 executionFlowReasonCode = "invalid_span_id"
	executionFlowReasonMissingFlowEnvironmentId      executionFlowReasonCode = "missing_flow_environment_id"
	executionFlowReasonMissingProducer               executionFlowReasonCode = "missing_producer"
	executionFlowReasonMissingRequiredAttribute      executionFlowReasonCode = "missing_required_attribute"
	executionFlowReasonMissingServiceInstance        executionFlowReasonCode = "missing_service_instance"
	executionFlowReasonMissingServiceLogicalInstance executionFlowReasonCode = "missing_service_logical_instance"
	executionFlowReasonNonBatchJob                   executionFlowReasonCode = "non-batch-job"
	executionFlowReasonPointNameMismatch             executionFlowReasonCode = "point_name_mismatch"
	executionFlowReasonProducerMismatch              executionFlowReasonCode = "producer_mismatch"
	executionFlowReasonRequeueAttempt                executionFlowReasonCode = "requeue-attempt"
	executionFlowReasonRequeueEnabled                executionFlowReasonCode = "requeue-enabled"
	executionFlowReasonStorageCapacityExceeded       executionFlowReasonCode = "storage_capacity_exceeded"
	executionFlowReasonUnexpectedAttribute           executionFlowReasonCode = "unexpected_attribute"
	executionFlowReasonUnknownPoint                  executionFlowReasonCode = "unknown_point"
)

var generatedExecutionFlowEnvelopeAttributes = map[string]executionFlowEnvelopeAttributeSpec{
	"event_sequence":           {Name: "event_sequence", Type: "int64", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonInvalidEventSequence},
	"flow_id":                  {Name: "flow_id", Type: "string", Requirement: executionFlowEnvelopeRequiredBusiness, MissingReason: executionFlowReasonInvalidFlowId},
	"flow_schema":              {Name: "flow_schema", Type: "string", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonInvalidFlowSchema},
	"point":                    {Name: "point", Type: "string", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonPointNameMismatch},
	"producer":                 {Name: "producer", Type: "string", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonMissingProducer},
	"service_instance":         {Name: "service_instance", Type: "string", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonMissingServiceInstance},
	"service_logical_instance": {Name: "service_logical_instance", Type: "string", Requirement: executionFlowEnvelopeRequiredAlways, MissingReason: executionFlowReasonMissingServiceLogicalInstance},
}

var generatedExecutionFlowStorageAttributes = map[string]executionFlowStorageAttributeSpec{
	"event_time_unix_nano": {Name: "event_time_unix_nano", Type: "int64", Kind: executionFlowStorageField, Source: "frontend", Wire: false, Minimum: 1, Maximum: 0, HasMinimum: true, HasMaximum: false},
	"flow_environment_id":  {Name: "flow_environment_id", Type: "string", Kind: executionFlowStorageTag, Source: "frontend", Wire: false, Minimum: 0, Maximum: 0, HasMinimum: false, HasMaximum: false},
	"flow_instance_slot":   {Name: "flow_instance_slot", Type: "int64", Kind: executionFlowStorageTag, Source: "frontend", Wire: false, Minimum: 0, Maximum: 63, HasMinimum: true, HasMaximum: true},
	"flow_slot":            {Name: "flow_slot", Type: "int64", Kind: executionFlowStorageTag, Source: "frontend", Wire: false, Minimum: 0, Maximum: 63, HasMinimum: true, HasMaximum: true},
}

var generatedExecutionFlowAttributeTypes = map[string]string{
	"attempt":     "int64",
	"job_id":      "int64",
	"node_id":     "string",
	"operation":   "enum",
	"outcome":     "enum",
	"reason_code": "enum",
	"status":      "int64",
	"step_id":     "int64",
	"task_id":     "int64",
}

var generatedExecutionFlowEnumValues = map[string]map[string]struct{}{
	"operation": {
		"alloc-jobs":              {},
		"alloc-steps":             {},
		"allocate":                {},
		"cancel-pending-job":      {},
		"daemon-cleanup":          {},
		"daemon-configure":        {},
		"daemon-terminal":         {},
		"embedded-db-commit":      {},
		"embedded-db-finalize":    {},
		"enqueue-status":          {},
		"execute-step":            {},
		"execute-steps":           {},
		"exit-supervisor":         {},
		"finalize-step":           {},
		"finalize-task":           {},
		"fork-supervisor":         {},
		"free-jobs":               {},
		"free-step":               {},
		"free-steps":              {},
		"initialize":              {},
		"initialize-supervisor":   {},
		"install-job":             {},
		"install-step":            {},
		"job-cleanup":             {},
		"job-terminal":            {},
		"mongodb-finalize":        {},
		"observe-supervisor-exit": {},
		"observe-task-exit":       {},
		"prepare-task":            {},
		"release-resources":       {},
		"remove-job":              {},
		"requeue":                 {},
		"send-status-change":      {},
		"shutdown-supervisor":     {},
		"spawn-task":              {},
		"state-machine":           {},
		"status-change":           {},
		"step-cleanup":            {},
		"step-configure":          {},
		"step-terminal":           {},
		"submit":                  {},
		"submit-common-step":      {},
		"supervisor-epilog":       {},
	},
	"outcome": {
		"accepted":          {},
		"applied":           {},
		"cleanup-failure":   {},
		"completed":         {},
		"craned-down":       {},
		"early-cancel":      {},
		"exit":              {},
		"exited":            {},
		"failure":           {},
		"persisted":         {},
		"pre-start-failure": {},
		"queued":            {},
		"rejected":          {},
		"requested":         {},
		"rpc-failure":       {},
		"signal":            {},
		"skipped":           {},
		"started":           {},
		"success":           {},
		"unsupported":       {},
	},
	"reason_code": {
		"array-job":                        {},
		"cancelled-before-allocation":      {},
		"container-job":                    {},
		"extra-common-step":                {},
		"flow_environment_id_mismatch":     {},
		"invalid_attribute_type":           {},
		"invalid_enum_value":               {},
		"invalid_event_sequence":           {},
		"invalid_event_time":               {},
		"invalid_flow_id":                  {},
		"invalid_flow_schema":              {},
		"invalid_integer_attribute":        {},
		"invalid_span_id":                  {},
		"missing_flow_environment_id":      {},
		"missing_producer":                 {},
		"missing_required_attribute":       {},
		"missing_service_instance":         {},
		"missing_service_logical_instance": {},
		"non-batch-job":                    {},
		"point_name_mismatch":              {},
		"producer_mismatch":                {},
		"requeue-attempt":                  {},
		"requeue-enabled":                  {},
		"storage_capacity_exceeded":        {},
		"unexpected_attribute":             {},
		"unknown_point":                    {},
	},
}

var generatedExecutionFlowPoints = map[string]executionFlowPointSpec{
	"craned/job/installed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"craned/job/removed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"craned/status/send_result": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"craned/step/cleanup_finished": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/cleanup_started": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation"},
	},
	"craned/step/execute_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/free_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/install_accepted": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/step/installed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/exit_observed": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/forked": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"craned/supervisor/ready": {
		Producer:           "craned",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/accepted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/alloc_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/allocated": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/allocation_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/embedded_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/free_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "node_id", "operation", "outcome"},
	},
	"ctld/job/mongo_persisted": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/resources_released": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome"},
	},
	"ctld/job/terminal": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "status", "operation", "outcome"},
	},
	"ctld/job/unsupported": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "operation", "outcome", "reason_code"},
	},
	"ctld/status/applied": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"ctld/status/received": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"ctld/step/all_completing": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "operation", "outcome"},
	},
	"ctld/step/all_configured": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "operation", "outcome"},
	},
	"ctld/step/all_terminal": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "status", "operation"},
	},
	"ctld/step/alloc_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/execute_requested": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/execute_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"ctld/step/free_rpc_result": {
		Producer:           "cranectld",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"pipeline/fault": {
		Producer:           "frontend",
		RequiredAttributes: []string{"reason_code"},
	},
	"supervisor/step/all_tasks_finalized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/step/completing_enqueued": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/step/epilog_finished": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"supervisor/step/execute_started": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "operation", "outcome"},
	},
	"supervisor/step/exiting": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/step/initialized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/step/shutdown_received": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "node_id", "status", "operation"},
	},
	"supervisor/task/exit_observed": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
	"supervisor/task/finalized": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "status", "operation", "outcome"},
	},
	"supervisor/task/prepared": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
	"supervisor/task/spawned": {
		Producer:           "supervisor",
		RequiredAttributes: []string{"job_id", "step_id", "task_id", "node_id", "operation", "outcome"},
	},
}

type generatedExecutionFlowCatalogData struct{}

var generatedExecutionFlowCatalog executionFlowSchemaCatalog = generatedExecutionFlowCatalogData{}

func (generatedExecutionFlowCatalogData) SchemaSHA256() string {
	return executionFlowSchemaSHA256
}

func (generatedExecutionFlowCatalogData) SchemaName() string {
	return executionFlowSchemaName
}

func (generatedExecutionFlowCatalogData) SchemaVersion() string {
	return executionFlowSchemaVersion
}

func (generatedExecutionFlowCatalogData) WirePrefix() string {
	return executionFlowWirePrefix
}

func (generatedExecutionFlowCatalogData) HeartbeatPoint() string {
	return executionFlowHeartbeatPoint
}

func (generatedExecutionFlowCatalogData) PipelineFaultPoint() string {
	return executionFlowPipelineFaultPoint
}

func (generatedExecutionFlowCatalogData) Point(name string) (executionFlowPointSpec, bool) {
	point, ok := generatedExecutionFlowPoints[name]
	if !ok {
		return executionFlowPointSpec{}, false
	}
	point.RequiredAttributes = append([]string(nil), point.RequiredAttributes...)
	return point, ok
}

func (generatedExecutionFlowCatalogData) EnvelopeAttributeType(name string) (string, bool) {
	attribute, ok := generatedExecutionFlowEnvelopeAttributes[name]
	return attribute.Type, ok
}

func (generatedExecutionFlowCatalogData) AllowsEnvelopeAttribute(name string) bool {
	_, ok := generatedExecutionFlowEnvelopeAttributes[name]
	return ok
}

func (generatedExecutionFlowCatalogData) EnvelopeAttributes() []executionFlowEnvelopeAttributeSpec {
	return []executionFlowEnvelopeAttributeSpec{
		generatedExecutionFlowEnvelopeAttributes["event_sequence"],
		generatedExecutionFlowEnvelopeAttributes["flow_id"],
		generatedExecutionFlowEnvelopeAttributes["flow_schema"],
		generatedExecutionFlowEnvelopeAttributes["point"],
		generatedExecutionFlowEnvelopeAttributes["producer"],
		generatedExecutionFlowEnvelopeAttributes["service_instance"],
		generatedExecutionFlowEnvelopeAttributes["service_logical_instance"],
	}
}

func (generatedExecutionFlowCatalogData) StorageAttribute(name string) (executionFlowStorageAttributeSpec, bool) {
	attribute, ok := generatedExecutionFlowStorageAttributes[name]
	return attribute, ok
}

func (generatedExecutionFlowCatalogData) AllowsStorageAttribute(name string) bool {
	_, ok := generatedExecutionFlowStorageAttributes[name]
	return ok
}

func (generatedExecutionFlowCatalogData) StorageAttributes() []executionFlowStorageAttributeSpec {
	return []executionFlowStorageAttributeSpec{
		generatedExecutionFlowStorageAttributes["event_time_unix_nano"],
		generatedExecutionFlowStorageAttributes["flow_environment_id"],
		generatedExecutionFlowStorageAttributes["flow_instance_slot"],
		generatedExecutionFlowStorageAttributes["flow_slot"],
	}
}

func (generatedExecutionFlowCatalogData) AttributeType(name string) (string, bool) {
	attributeType, ok := generatedExecutionFlowAttributeTypes[name]
	return attributeType, ok
}

func (generatedExecutionFlowCatalogData) AllowsAttribute(name string) bool {
	_, ok := generatedExecutionFlowAttributeTypes[name]
	return ok
}

func (generatedExecutionFlowCatalogData) AllowsEnumValue(attribute string, value string) bool {
	values, ok := generatedExecutionFlowEnumValues[attribute]
	if !ok {
		return false
	}
	_, ok = values[value]
	return ok
}
