# Toggle the plugin module in CraneSched
Enabled: true

# Relative to CraneBaseDir
PlugindSockPath: "cranectld/cplugind.sock"
PlugindDebugLevel: "trace"

# Plugins to be loaded in Plugind
Plugins:
  - Name: "dummy"
    Path: "/path/to/dummy.so"
    Config: "/path/to/dummy.yaml"