name: Test

on:
  push:
    branches: [ "master" ]
    paths:
    - "**/*.go"
    - "**/*.proto"
  pull_request:
    branches: [ "master" ]
    paths:
    - "**/*.go"
    - "**/*.proto"
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: Upload artifact
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nativu5/cranedev:ci
      credentials:
         username: ${{ github.actor }}
         password: ${{ github.token }}
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache Go pkg
        uses: actions/cache@v4
        with:
          path: |
            /root/go
            /root/.cache/go-build
          key: ${{ runner.os }}-gopkg-${{ hashFiles('go.sum') }}

      # https://github.com/docker-library/golang/issues/452
      - name: Set workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Build
        run: make all |& tee build.log

      - name: Upload artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            ./build/
            ./build.log
          if-no-files-found: error
          retention-days: 30
          overwrite: true
